Update scaamain.yml

diff --git a/.github/workflows/scaamain.yml b/.github/workflows/scaamain.yml
--- a/.github/workflows/scaamain.yml
+++ b/.github/workflows/scaamain.yml
@@ -8,7 +8,7 @@ on:
 
 jobs:
   sca-scan:
-    name: Run CxSCA Scan using Resolver
+    name: CxSCA Scan using Resolver
     runs-on: ubuntu-latest
 
     steps:
@@ -21,15 +21,14 @@ jobs:
           java-version: '17'
           distribution: 'temurin'
 
-      - name: Download latest CxSCA Resolver (via wget)
+      - name: Download CxSCA Resolver from Maven Central
         run: |
-          wget https://github.com/CheckmarxDev/sca-resolver/releases/latest/download/CxSCAResolver.jar -O CxSCAResolver.jar
+          wget https://repo1.maven.org/maven2/com/checkmarx/sca/resolver/CxSCAResolver/2.1.46/CxSCAResolver-2.1.46.jar -O CxSCAResolver.jar
           file CxSCAResolver.jar
           if [ ! -s CxSCAResolver.jar ]; then
-          echo "❌ Downloaded JAR is invalid or empty"
-          exit 1
+            echo "❌ Downloaded JAR is invalid or empty"
+            exit 1
           fi
-
 
       - name: Run CxSCA Scan
         run: |
